-id: w100_update
alias: W100 Update
triggers:
  - entity_id:
      - sensor.living_room_thermostat_pmtsd_from_w100_data
    trigger: state
conditions:
  - condition: template
    value_template: >
      {% set bad = ['unknown', 'unavailable', 'none', ''] %} {{
      trigger.to_state.state not in bad and trigger.to_state.state !=
      trigger.from_state.state and not (trigger.from_state.state in bad and
      trigger.to_state.state not in bad) }}
actions:
  - action: script.w100_to_pmtsd
    data: {}
  - action: script.pmtsd_to_ce
    data: {}
  - delay:
      milliseconds: 500
  - action: script.ce_to_pmtsd
    data: {}
  - action: script.pmstd_to_w100
    data: {}
mode: single

-id: w100_pmtsd_request
alias: W100 PMSTD Request
description: ""
triggers:
  - trigger: mqtt
    topic: zigbee2mqtt/Living Room Thermostat/action
    payload: W100_PMTSD_request
conditions: []
actions:
  - action: script.ce_to_pmtsd
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - action: script.pmstd_to_w100
    data: {}
mode: single

-id: thermostat_update
alias: Thermostat Update
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.living_room_ac
    attribute: temperature
  - trigger: state
    entity_id:
      - climate.living_room_ac
    attribute: hvac_action
  - trigger: state
    entity_id:
      - climate.living_room_ac
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - action: script.ce_to_pmtsd
    data: {}
  - action: script.pmstd_to_w100
    data: {}
mode: queued
